version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\Protacon.RxMq.Abstractions\artifacts\**\*.nupkg
  name: NuGet
- path: .\Protacon.RxMq.AzureServiceBus\artifacts\**\*.nupkg
  name: NuGet
- path: .\Protacon.RxMq.AzureServiceBusLegacy\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: AcGQeBVVsXFTv0cJ4Jo0q6dKMcAmqXX2V5eDBk1tittf3oh/iaH3VqMTEd+3F+Qw
  on:
    branch: master
    appveyor_repo_tag: true