trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isTagBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: build solutions
  inputs:
    command: 'build'

- task: DownloadSEcureFile@1
  name: devSettings
  displayName: fetch development settings
  inputs:
    secureFile: 'development-settings.json'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/Testing/Prepare-environment.ps1'
    arguments: 
      -settingsFile $(devSettings.secureFilePath)
  displayName: 'create environment'

    