trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isTagBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: build solutions
  inputs:
    command: 'build'

- task: DownloadSEcureFile@1
  name: devSettings
  displayName: fetch development settings
  inputs:
    secureFile: 'developer-settings.json'
- task: AzurePowerShell@4
  displayName: 'create environment'
  inputs:
    azureSubscription: my-arm-service-connection
    scriptType: filePath
    scriptPath: '$(Build.SourcesDirectory)/Testing/Prepare-environment.ps1'
    scriptArguments:
      -settingsFile $(devSettings.secureFilePath)
    azurePowerShellVersion: latestVersion


    