trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Pack Abstractions library'
  inputs:
    command: 'pack'
    packagesToPack: 'Protacon.RxMq.Abstractions.csproj/Protacon.RxMq.Abstractionsj.csproj'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Pack Legacy library'
  inputs:
    command: 'pack'
    packagesToPack: 'Protacon.RxMq.AzureServiceBusLegacy/Protacon.RxMq.AzureServiceBusLegacy.csproj'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Pack Modern library'
  inputs:
    command: 'pack'
    packagesToPack: 'Protacon.RxMq.AzureServiceBus/Protacon.RxMq.AzureServiceBus.csproj'
    configuration: '$(buildConfiguration)'
