trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isTagBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: build solutions
  inputs:
    command: 'build'

- task: DownloadSEcureFile@1
  name: devSettings
  displayName: fetch development settings
  inputs:
    secureFile: 'developer-settings.json'

- task: AzurePowerShell@5
  displayName: create environment
  inputs:
    azureSubscription: 'Development-use'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/Testing/Prepare-environment.ps1'
    ScriptArguments: '-settingsFile $(devSettings.secureFilePath)'
    azurePowerShellVersion: 'LatestVersion'
    
- task: AzurePowerShell@5
  displayName: create secrets
  inputs:
    azureSubscription: 'Development-use'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/Create-ClientSecrets.ps1'
    ScriptArguments: '-settingsFile $(devSettings.secureFilePath)'
    azurePowerShellVersion: 'LatestVersion'
    
- task: DotNetCoreCLI@2
  displayName: tests
  inputs:
    command: test
    projects: '**/*AzureServiceBus.test*.csproj'
    
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)/Protacon.RxMq.AzureServiceBusLegacy.Tests'




    

    
  
   


    