trigger:
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isTagBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  buildNumber: $[replace(variables['build.BuildNumber'], '.', '')]
  envName: 'RxMqTestEnvironment$(buildNumber)'

jobs:
- job: 'build'
  steps:
  - task: DotNetCoreCLI@2
    displayName: restore
    inputs:
      command: 'restore'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: build solutions
    inputs:
      command: 'build'
  
  - task: DownloadSEcureFile@1
    name: devSettings
    displayName: fetch development settings
    inputs:
      secureFile: 'developer-settings.json'
  - task: AzurePowerShell@5
    displayName: create environment
    inputs:
      azureSubscription: 'Development-use'
      ScriptType: 'FilePath'
      ScriptPath: '$(Build.SourcesDirectory)/Testing/Prepare-environment.ps1'
      ScriptArguments:
        -SettingsFile $(devSettings.secureFilePath) `
        -EnvironmentName $(envName)
      azurePowerShellVersion: 'LatestVersion'
      
  - task: AzurePowerShell@5
    displayName: create secrets
    inputs:
      azureSubscription: 'Development-use'
      ScriptType: 'FilePath'
      ScriptPath: '$(Build.SourcesDirectory)/Create-ClientSecrets.ps1'
      ScriptArguments:
        -SettingsFile $(devSettings.secureFilePath) `
        -EnvironmentName $(envName)
      azurePowerShellVersion: 'LatestVersion'
      
  - task: DotNetCoreCLI@2
    displayName: tests
    inputs:
      command: test
      projects: '**/*test*.csproj'
             
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: remove environment
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Development-use'
      subscriptionId: '594dd722-b5c7-449c-91ae-e9ab9a54b660'
      action: 'DeleteRG'
      resourceGroupName: $(envName)
    