trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isTagBuild: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

steps:
- task: DotNetCoreCLI@2
  displayName: build solutions
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: build solutions
  inputs:
    command: 'build'
    

    